# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 244ddb95f61eb7ede3c0176f3c4e5c83a124e55c9d589efc89b04ac37a9d997a2fd63a673c8c6242072a54bc8e10ba3d7d64af6535f14ff9565eaeb5f3ef00f1

test:
  secret_key_base: a786984cb60fbe7d2e5be72f85121354b0177075798fc863ef883a621f732cbea6a0b103cb60756b6cc116c6df01c30ee3e83399266c112d9c7088a14591ed9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
